---
#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"
#
- name: Ensure saphana pattern is installed
  ansible.builtin.zypper:
    type: pattern
    name: sap-hana
    state: present
    force: yes

- name: Ensure saptune is installed
  ansible.builtin.zypper:
    type: package
    name: "saptune={{ sap_hana_preconfigure_saptune_version }}"
    state: present
    force: yes
